apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-registration
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - update
- apiGroups:
  - "cluster.open-cluster-management.io"
  resources:
  - managedclusters
  - managedclusters/status
  verbs:
  - get  
  - update
  - patch
- apiGroups:
  - "work.open-cluster-management.io"
  resources:
  - manifestworks
  verbs:
  - get  
  - update
- apiGroups:
  - "work.open-cluster-management.io"
  resources:
  - manifestworks/status
  verbs:
  - patch  
  - update
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - create  
  - get    
- apiGroups:
  - "register.open-cluster-management.io"
  resources:
  - managedclusters/clientcertificates
  verbs:
  - renew
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - managedclusteraddons
  verbs:
  - get
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - managedclusteraddons/status
  verbs:
  - patch
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - update       

  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:cluster-manager-registration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cluster-manager-registration
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager

