apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mynginx
  labels:
    cluster.open-cluster-management.io/appbundle: mybundle
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.5
          ports:
            - containerPort: 80