apiVersion: apps/v1
kind: Deployment
metadata:
  clusterName: admin
  name: deployment1
  labels:
    kcp.dev/group: group1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"    