apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: {{ .clusterName }}
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: {{ .clusterPort }}
    hostPort: {{ .clusterPort }}
    listenAddress: "0.0.0.0" 
    protocol: tcp