apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command:
    - sleep
    - "1000000"
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: cm-kubeconfig
  volumes:
  - name: cm-kubeconfig
    secret: 
      secretName: cm-kubeconfig    